server:
  port: 8080
spring:
  application:
    name: japanese-app
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  #hibernate
  datasource:
    hikari:
      maximum-pool-size: 20
      minimun-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: JP-HikariPool
  mvc:
    apiVersion:
      use:
        path-segment: 2
      supported: 1.0
      default: 1.0
#logging:
#  level:
#    org.springframework.web: TRACE
#    org.springframework.security: TRACE

# swagger config
springdoc:
  swagger-ui:
    path: ${swagger.base.path}/v1/api-docs
  api-docs:
    path: ${swagger.base.path}/v1
#custom config
api:
  base:
    path: /japanese-app/api
swagger:
  base:
    path: /japanese-app/swagger
