server:
  port: 8080
spring:
  application:
    name: japanese-app
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  #api versioning
  mvc:
    apiVersion:
      use:
        path-segment: 2
      supported: 1
      default: 1

#custom config
api:
  base:
    path: japanese-app/api
