server:
  port: 8080
spring:
  application:
    name: japanese-app
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  mvc:
    apiVersion:
      use:
        path-segment: 2
      supported: 1.0
      default: 1.0
#logging:
#  level:
#    org.springframework.web: TRACE
#    org.springframework.security: TRACE

#custom config
api:
  base:
    path: /japanese-app/api
